{% set name = "boa-framework" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 292d6de71d7b2969723d762b6305c15e6dcf10498484bd88899759f656aa5a84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=34.4
    - setuptools-scm
  run:
    - python >=3.8
    - pytorch >=2.0
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - click
    - panel
    - plotly >=5.10.0
    - notebook >=5.3
    - ipywidgets >=7.5
    - ax-platform >=0.3.1,<=0.3.4
    - ruamel.yaml
    - attrs
    - jinja2


test:
  imports:
    - boa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/madeline-scyphers/boa
  summary: Bayesian Optimization for Anything
  description: |
    Bayesian Optimization for Anything: A high-level Bayesian optimization framework and model wrapping tool.
    It provides an easy-to-use interface between models and the python libraries Ax and BoTorch.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pyboa.readthedocs.io
  dev_url: https://github.com/madeline-scyphers/boa

extra:
  recipe-maintainers:
    - madeline-scyphers
    - jemissik
