{% set name = "boa-framework" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52b1e2842e52fbbad70cad0ef05c65e316a2e4b07d5be09b907f93c949ea85a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=34.4
    - setuptools-scm
  run:
    - python >=3.8
    - pytorch >=2.0
    - botorch ==0.8.5
    - gpytorch ==1.10
    - linear_operator ==0.4.0
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - click
    - panel
    - plotly >=5.10.0
    - notebook >=5.3
    - ipywidgets >=7.5
    - ax-platform ==0.3.3
    - ruamel.yaml
    - attrs


test:
  imports:
    - boa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/madeline-scyphers/boa
  summary: Bayesian Optimization for Anything
  description: |
    Bayesian Optimization for Anything: A high-level Bayesian optimization framework and model wrapping tool.
    It provides an easy-to-use interface between models and the python libraries Ax and BoTorch.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pyboa.readthedocs.io
  dev_url: https://github.com/madeline-scyphers/boa

extra:
  recipe-maintainers:
    - madeline-scyphers
    - jemissik
